import Feed from '../components/Feed'
import Login from '@/components/Login'
import SideBar from '@/components/SideBar'
import { useSession } from 'next-auth/react'
import Head from 'next/head'


export default function Home() {

  const {data: session} = useSession()

  if(!session) return <Login />

  return (
    <>
      <Head>
        <title>Twitter-clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' relative max-w-[1400px] mx-auto'>
        <SideBar/>
        <div className=' flex gap-6' >
          <Feed/>
        </div>
      </main>
    </>
  )
}
